# Generated by Django 5.0.4 on 2024-04-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('roll_number', models.CharField(blank=True, max_length=10)),
                ('marks', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=1)),
                ('result', models.CharField(max_length=100)),
            ],
        ),
    ]
